language: android
jdk: oraclejdk8
sudo: required # false for Container-Based Infrastructure, required for Sudo-enabled Infrastructure
dist: trusty

env:
  global:
    - PROJECT_NAME=sxrsdk
    - PROJECT_DIR=${TRAVIS_BUILD_DIR} # Project direct
    
before_install:   
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
  # newest Android NDK
  - wget https://dl.google.com/android/repository/android-ndk-r18b-linux-x86_64.zip -O ndk.zip
  - unzip ndk.zip  > /dev/null 2>&1
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-r18b
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_NDK_HOME}
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-25.0.3
    - android-25
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

install:
    - git clone  https://sxrsdk:82c3775188fc23e31abd0d3e8db8fd499f17af34@github.com/sxrsdk/sxrsdk-demos.git $PROJECT_DIR/demos

before_script:
    - cd $PROJECT_DIR/SXR/SDK
    - echo "only_monoscopic=true" >> gradle.properties
    - echo "useLocalDependencies=true" >> gradle.properties
    - cd $PROJECT_DIR/SXR/Extensions
    - echo "only_monoscopic=true" >> gradle.properties
    - echo "useLocalDependencies=true" >> gradle.properties
      
script:
    - cd $PROJECT_DIR/SXR/SDK
    - ./gradlew assembleDebug
    - cd $PROJECT_DIR/SXR/Extensions
    - ./gradlew assembleDebug
    - cd $PROJECT_DIR/demos
    - ./gradlew assembleMonoscopicDebug
